"""add ner_path to documents

Revision ID: 5ea1bb7e236a
Revises: b8e3f2a1c4d5
Create Date: 2026-07-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea1bb7e236a'
down_revision = 'b8e3f2a1c4d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ner_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ner_path')
    # ### end Alembic commands ###
