"""add converted_path to documents

Revision ID: 70bce243b736
Revises: 1b139bb7a734
Create Date: 2026-06-08 01:48:49.900386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bce243b736'
down_revision = '1b139bb7a734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('converted_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'converted_path')
    # ### end Alembic commands ###
