"""add cleaned_path to documents

Revision ID: 8d638c6030d1
Revises: 70bce243b736
Create Date: 2026-06-08 02:26:26.493703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d638c6030d1'
down_revision = '70bce243b736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cleaned_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cleaned_path')
    # ### end Alembic commands ###
