"""add images_path to documents

Revision ID: cfe959221fc7
Revises: 8d638c6030d1
Create Date: 2026-06-12 01:11:19.982964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe959221fc7'
down_revision = '8d638c6030d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('images_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'images_path')
    # ### end Alembic commands ###
